# -*- coding: utf-8 -*-
"""Itinerum Model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vJAQYg_Qi1FrIhS5OXh_m1HRyaAdlass
"""

from keras.models import Sequential  
from keras.layers import Dense  
from keras.layers import LSTM  
from keras.layers import Dropout  
import numpy as np

model = Sequential()
num_datapoints = 2100
num_time_steps = 125
num_features = 6
num_classes = 6
batch_size = 25

train_inputs = np.random.randn(num_datapoints,num_time_steps,num_features)
labels = np.eye(num_classes)[np.random.choice(num_classes, num_datapoints)]
print(labels)

model.add(LSTM(units=20, input_shape=(num_time_steps, num_features)))  
#model.add(Dropout(0.2)) 
model.add(Dense(units = 10))
#model.add(Dropout(0.2))
model.add(Dense(units = num_classes))  

model.summary()

model.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics=['accuracy'])  
model.fit(train_inputs, labels, epochs = 10, batch_size=batch_size)  
model.predict(train_inputs)



test_inputs = np.random.randn(500,125,6)
model.predict(test_inputs)